config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

# from django.contrib.auth import views as auth_views

urlpatterns = [
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("", include("labs_booking.scheduler.urls")),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("labs_booking.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

desk_booking/core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

labs_booking/scheduler/urls.py
from datetime import datetime

from django.urls import path, register_converter

from labs_booking.scheduler import views
from labs_booking.scheduler.views import (
    SessionCancelView,
    SessionCreateView,
    SessionDetailView,
    SessionEditView,
    SessionListView,
)


class DateConverter:
    regex = r"\d{4}-\d{2}-\d{2}"

    def to_python(self, value):
        return datetime.strptime(value, "%Y-%m-%d")

    def to_url(self, value):
        return value


register_converter(DateConverter, "yyyy")

urlpatterns = [
    path("", SessionCreateView.as_view(), name="session-create"),
    path("about/", views.about, name="scheduler-about"),
    path("sessions/", SessionListView.as_view(), name="scheduler-sessions"),
    path("sessions/<int:pk>/", SessionDetailView.as_view(), name="session-detail"),
    path(
        "sessions/new/<yyyy:date>/",
        SessionCreateView.as_view(),
        name="session-create-date",
    ),
    path(
        "sessions/new/<yyyy:date>/<str:timeblock>",
        SessionCreateView.as_view(),
        name="session-create-spec",
    ),
    path("sessions/<int:pk>/edit", SessionEditView.as_view(), name="session-edit"),
    path(
        "sessions/<int:pk>/cancel", SessionCancelView.as_view(), name="session-cancel"
    ),
    path("issues/", views.report_issues, name="scheduler-issues"),
]

labs_booking/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from labs_booking.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
]

labs_booking/scheduler/models.py
from datetime import date

# from django.contrib.auth.models import User
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone

User = settings.AUTH_USER_MODEL


class Session(models.Model):

    TIMEBLOCK_CHOICES = (
        ("A", "8:00-9:00"),
        ("B", "9:00-10:00"),
        ("C", "10:00-11:00"),
        ("D", "11:00-12:00"),
        ("E", "12:00-13:00"),
        ("F", "13:00-14:00"),
        ("G", "14:00-15:00"),
        ("H", "15:00-16:00"),
        ("I", "16:00-17:00"),
        ("J", "17:00-18:00"),
        ("K", "18:00-19:00"),
        ("L", "19:00-20:00"),
    )

    LABS = (
        ("Quantum Computing Workstation","Quantum Computing Workstation"),
        ("X-ray Diffraction Workstation","X-ray Diffraction Workstation"),
        ("Nuclear Magnetic Resonance Workstation","Nuclear Magnetic Resonance Workstation"),
        ("Particle Accelerator Workstation","Particle Accelerator Workstation")
    )

    student = models.ForeignKey(User, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)
    date = models.DateField(default=timezone.now)
    timeblock = models.CharField(max_length=10, choices=TIMEBLOCK_CHOICES, default="A")

    lab_workstation = models.CharField(max_length=40, choices=LABS, default="A")
    operator_licence = models.CharField(max_length=30, default="")
    additional_info = models.CharField(max_length=50, default="")

    # @property
    def is_upcoming(self):
        return date.today() <= self.date

    is_upcoming.admin_order_field = "date"
    is_upcoming.boolean = True
    is_upcoming.short_description = "Session in the future?"

    @property
    def get_weekday(self):
        return self.date.strftime("%A")

    def __str__(self) -> str:
        return f"{self.student.username}: {self.date} ({self.timeblock})"

    def get_absolute_url(self):
        # returns a complete url string and let view handle the redirect
        return reverse("session-detail", kwargs={"pk": self.pk})


# REF: READ https://docs.djangoproject.com/en/4.0/topics/db/models/
class DayBlock(models.Model):
    date = models.DateField(default=timezone.now)
    # onduty = models.OneToOneField(Lab, on_delete=models.CASCADE, default="")
    # allBlocks = Session.objects.filter(date=date)
    # blockA = allBlocks.filter(timeblo)
    # blockB = models.OneToOneField(Lab, on_delete=models.CASCADE, default='')
    # blockC = models.OneToOneField(Lab, on_delete=models.CASCADE, default='')
    # blockD = models.OneToOneField(Lab, on_delete=models.CASCADE, default='')
    # blockE = models.OneToOneField(Lab, on_delete=models.CASCADE, default='')
    # blockF = models.OneToOneField(Lab, on_delete=models.CASCADE, default='')


class Issue(models.Model):
    email = models.EmailField()
    issue = models.TextField()
    user_agent = models.CharField(max_length=200)
    date_posted = models.DateTimeField(default=timezone.now)

    # dunder STR
    def __str__(self):
        return self.email

labs_booking/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for Tutor Scheduler."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = CharField(_("firstname"), blank=True, max_length=255)  # type: ignore
    last_name = CharField(_("lastname"), blank=True, max_length=255)  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})


class Lab(models.Model):
    WEEKDAY_CHOICES = (
        ("MONDAY", "Monday"),
        ("TUESDAY", "Tuesday"),
        ("WEDNESDAY", "Wednesday"),
        ("THURSDAY", "Thursday"),
        ("FRIDAY", "Friday"),
        ("SATURDAY", "Saturday"),
        ("SUNDAY", "Sunday"),
    )

    lab = models.ForeignKey(User, on_delete=models.CASCADE)
    dept = models.CharField(max_length=100)
    assigned_day = models.CharField(
        max_length=10, choices=WEEKDAY_CHOICES, default="MONDAY"
    )

    def __str__(self):
        return self.assigned_day

    def get_name(self):
        return self.lab.first_name + " " + self.lab.last_name

labs_booking/scheduler/forms.py
from django import forms

from .models import Issue, Session


class IssuesForm(forms.ModelForm):
    email = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "i.e. smitht24@gmail.com"})
    )

    class Meta:
        model = Issue
        fields = ["email", "issue", "user_agent"]


class SessionForm(forms.ModelForm):
    date = forms.DateField(disabled=False)
    # timeblock = forms.CharField(disabled=True)
    operator_licence = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Enter the number of your license (if applicable)"}), required=False
    )
    additional_info = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "i.e. I require assistance as I am unfamiliar with this workstation"}), required=False
    )

    class Meta:
        model = Session
        fields = ["date", "timeblock", "lab_workstation", "operator_licence", "additional_info"]
        # fields = ["date", "timeblock", "operator_licence", "additional_info"]        

    # REF: https://stackoverflow.com/questions/23690450/django-prevent-duplicates-for-users
    # def clean(self):
    #     # if Session.objects.filter(student=self.user, date=self.date).exists():
    #     #     raise forms.ValidationError(
    #     #         "Cannot schedule more than one session on a single day!"
    #     #     )
    #     if Session.objects.filter(date=self.date, timeblock=self.timeblock).exists():
    #         raise forms.ValidationError("That date & time is already booked!")
 

labs_booking/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

labs_booking/scheduler/views.py
import datetime

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from labs_booking.scheduler.forms import IssuesForm, SessionForm
from labs_booking.scheduler.models import Session
from labs_booking.users.models import Lab


def generate_daylist():
    daylist = []
    today = datetime.date.today()
    for i in range(7):
        day = {}
        curr_day = today + datetime.timedelta(days=i)
        weekday = curr_day.strftime("%A").upper()
        lab = Lab.objects.filter(assigned_day=weekday).first()
        day["date"] = str(curr_day)
        day["day"] = weekday
        #day["onduty"] = lab.get_name()
        #day["dept"] = lab.dept
        day["A_booked"] = (
            Session.objects.filter(date=str(curr_day)).filter(timeblock="A").exists()
        )
        day["B_booked"] = (
            Session.objects.filter(date=str(curr_day)).filter(timeblock="B").exists()
        )
        day["C_booked"] = (
            Session.objects.filter(date=str(curr_day)).filter(timeblock="C").exists()
        )
        day["D_booked"] = (
            Session.objects.filter(date=str(curr_day)).filter(timeblock="D").exists()
        )
        day["E_booked"] = (
            Session.objects.filter(date=str(curr_day)).filter(timeblock="E").exists()
        )
        day["F_booked"] = (
            Session.objects.filter(date=str(curr_day)).filter(timeblock="F").exists()
        )
        if day["day"] != "SATURDAY":  # Writing lab doesn't open on Saturday
            daylist.append(day)
    return daylist


class SessionListView(ListView):
    model = Session
    template_name = "scheduler/sessions.html"  # <app>/<model>_<view_type>.html
    context_object_name = "sessions"
    ordering = ["-date"]


# saving code by following conventions
class SessionDetailView(DetailView):
    model = Session


# note: mixins should come before CreateView
class SessionCreateView(LoginRequiredMixin, CreateView):
    # model = Session
    # fields = ["date", "timeblock", "lab_workstation", "operator_licence", "additional_info"]
    form_class = SessionForm
    template_name = "scheduler/session_form.html"

    def form_valid(self, form):
        form.instance.student = self.request.user
        return super().form_valid(form)

    def get_initial(self):
        return {
            "date": self.kwargs.get("date"),
            "timeblock": self.kwargs.get("timeblock"),
        }

    def get_success_url(self):
        return reverse("users:detail", args=[self.request.user.username])

    # def get_form_kwargs(self, *args, **kwargs):  # forms.py def clean()
    #     kwargs = super(SessionCreateView, self).get_form_kwargs(*args, **kwargs)
    #     kwargs["user"] = self.request.user
    #     return kwargs


class SessionEditView(
    SuccessMessageMixin, LoginRequiredMixin, UserPassesTestMixin, UpdateView
):
    model = Session
    fields = ["lab_workstation", "operator_licence", "additional_info"]
    # fields = ["operator_licence", "additional_info"]
    # success_url = "/users/<str:username>/"
    success_message = "Reservation was updated successfully"

    def form_valid(self, form):
        form.instance.student = self.request.user
        return super().form_valid(form)

    def test_func(self):
        session = self.get_object()
        if self.request.user == session.student:
            return True
        return False

    def get_success_url(self):
        return reverse("users:detail", args=[self.request.user.username])


class SessionCancelView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Session

    def test_func(self):
        session = self.get_object()
        if self.request.user == session.student:
            return True
        return False

    def get_success_url(self):
        return reverse("users:detail", args=[self.request.user.username])


def home(request):
    context = {"days": generate_daylist()}
    return render(request, "scheduler/session_form.html", context)


def about(request):
    return render(request, "pages/about.html")


def sessions(request):
    context = {"sessions": Session.objects.all()}
    return render(request, "scheduler/sessions.html", context)


def report_issues(request):
    if request.method == "POST":
        form = IssuesForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Successfully reported issue!")
            return redirect("scheduler-home")
    else:  # displays empty form initially
        form = IssuesForm()

    return render(request, "scheduler/report_issues.html", {"form": form})

labs_booking/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

from labs_booking.scheduler.models import Session

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # TODO: get user object
    # user = request.user
    slug_field = "username"
    slug_url_kwarg = "username"

    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        context[
            "user_group"
        ] = "Student"  # "Lab" if user.groups.filter(name="lab") else "Student",
        context[
            "user_sessions"
        ] = Session.objects.all()  # Session.objects.filter(student=user)
        context["teacher_sessions"] = Session.objects.all()
        return context


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


# @login_required
# def profile(request):
#     user = request.user
#     context = {
#         "user_group": "Lab" if user.groups.filter(name="lab") else "Student",
#         "user_sessions": Session.objects.filter(student=user),
#         "lab": "",
#         "teacher_sessions": Session.objects.all(),
#     }
#     return render(request, "users/profile.html", context)

labs_booking/templates/users/profile.html
{% extends "base.html" %}
{% load static %}
{% load has_group %}
{% block title %}User: {{ user.username }}{% endblock %}

{% block content %}

<!-- Modal -->
<div class="modal fade" id="sessionDeleteModal" tabindex="-1" role="dialog" aria-labelledby="sessionDeleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Cancel Session</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to cancel this session?
                <!-- {% include "scheduler/session_confirm_delete.html" %} -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button class="btn btn-outline-danger" type="submit">Yes, Cancel</button>
            </div>
        </div>
    </div>
</div>

<div class="content-section">
    <h2>My Profile</h2>
    <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
            <h2 class="account-heading">{{ user.username }}</h2>
            <p class="text-secondary">{{ user_group }}</p>
            <p class="text-secondary">{{ user.email }}</p>
        </div>
    </div>
    <a href="{% url 'editprofile' %}">Edit my profile</a>
</div>

{% if user|has_group:"lab" %}
<div class="content-section">
    <h3>All Reservations</h3>
    {% for session in teacher_sessions %}
    <article class="media content-section">
        <img class='rounded-circle article-img' src="{{ session.student.profile.image.url }}">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="#">{{ session.student }}</a>
                <small class="text-muted">{{ session.date|date:"F d - l" }}</small>
            </div>
            <h4><a class="article-title" href="#">{{ session.timeblock }}</a></h4>
            <p class="article-content">{{ session.additional_info }}</p>
        </div>
    </article>
    {% endfor %}
</div>
{% else %}
<div class="content-section">
    <h3>Upcoming Reservations</h3>
    {% for session in user_sessions %}
    {% if session.is_upcoming %}
    <div class="card bg-light mb-3" style="width: 18rem;">
        <div class="card-header">{{ session.date|date:"F d, l" }}</div>
        <div class="card-body">
            <h5 class="card-title">{{ session.get_timeblock_display }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ session.lab_workstation }} ({{ session.operator_licence }})</h6>
            <p class="card-text">{{ session.additional_info }}</p>
            <a class='btn btn-outline-secondary btn-small mt-1 mb-1' href="{% url 'session-edit' session.id %}">Edit</a>
            <a class='btn btn-outline-danger btn-small mt-1 mb-1'
                href="{% url 'session-cancel' session.id %}">Cancel</a>
            <button type="button" class="btn btn-outline-danger btn-small mt-1 mb-1" data-toggle="modal"
                data-target="#sessionDeleteModal">
                Modal Cancel
            </button>
        </div>
    </div>
    {% endif %}
    {% endfor %}

    <h3>Past Reservations</h3>
    {% for session in user_sessions %}
    {% if session.is_upcoming is False %}
    <div class="card border-dark mb-3" style="width: 18rem;">
        <div class="card-header">{{ session.date|date:"F d, l" }}</div>
        <div class="card-body text-dark">
            <h5 class="card-title">{{ session.get_timeblock_display }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ session.lab_workstation }} ({{ session.operator_licence }})</h6>
            <p class="card-text">{{ session.additional_info }}</p>
        </div>
    </div>
    {% endif %}
    {% endfor %}
</div>
{% endif %}
{% endblock content %}

labs_booking/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}

<div class="content-section">
  <h2>My Profile</h2>
  <div class="media">
    <img class="rounded-circle account-img" src="{% static 'images/profilepic.png' %}">
      <div class="media-body">
          <h2 class="account-heading">{{ object.username }}</h2>
          <p class="text-secondary">{{ user_group }}</p>
          <p class="text-secondary">{{ object.email }}</p>
      </div>
  </div>
  <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">Edit Profile</a>
  <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">Edit Email</a>
</div>

<div class="content-section">
  <h3>Upcoming Reservations</h3>
  {% for session in user_sessions %}
  {% if session.is_upcoming %}
  <div class="card bg-light mb-3" style="width: 18rem;">
      <div class="card-header">{{ session.date|date:"F d, l" }}</div>
      <div class="card-body">
          <h5 class="card-title">{{ session.get_timeblock_display }}</h5>
          <h6 class="card-subtitle mb-2 text-muted">{{ session.lab_workstation }} ({{ session.operator_licence }})</h6>
          <p class="card-text">{{ session.additional_info }}</p>
          <a class='btn btn-outline-secondary btn-small mt-1 mb-1' href="{% url 'session-edit' session.id %}">Edit</a>
          <a class='btn btn-outline-danger btn-small mt-1 mb-1'
              href="{% url 'session-cancel' session.id %}">Cancel</a>
      </div>
  </div>
  {% endif %}
  {% endfor %}

  <h3>Past Reservations</h3>
  {% for session in user_sessions %}
  {% if session.is_upcoming is False %}
  <div class="card border-dark mb-3" style="width: 18rem;">
      <div class="card-header">{{ session.date|date:"F d, l" }}</div>
      <div class="card-body text-dark">
          <h5 class="card-title">{{ session.get_timeblock_display }}</h5>
          <h6 class="card-subtitle mb-2 text-muted">{{ session.lab_workstation }} ({{ session.operator_licence }})</h6>
          <p class="card-text">{{ session.additional_info }}</p>
      </div>
  </div>
  {% endif %}
  {% endfor %}
</div>

{% endblock content %}

labs_booking/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <a class="btn btn-outline-secondary" href="{% url 'users:detail' request.user.username  %}">Go Back</a>
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}